# Adds the corpus page to a copy of campfire: GET /_richtext/:id renders
# one stored message through campfire's OWN helpers — the
# `message_presentation` its message partial calls, and the body's plain
# text — between markers, with no layout. Applied to a copy of the Rails
# oracle tree and to the copy of campfire the emit is transpiled from, so
# both sides answer through the same code path, request stack included.
#
#   ruby tests/richtext_corpus/overlay.rb <campfire copy>
app = ARGV.fetch(0)

File.write(File.join(app, "app/controllers/richtext_corpus_controller.rb"), <<~RUBY)
  # GENERATED by roundhouse's tests/richtext_corpus/overlay.rb — not part of campfire.
  class RichtextCorpusController < ApplicationController
    allow_unauthenticated_access
    skip_forgery_protection

    def show
      @message = Message.find(params[:id])
      render layout: false
    end
  end
RUBY

dir = File.join(app, "app/views/richtext_corpus")
Dir.mkdir(dir) unless Dir.exist?(dir)
File.write(File.join(dir, "show.html.erb"), <<~ERB)
  <!--RC:presentation--><%= message_presentation(@message) %><!--/RC:presentation-->
  <!--RC:plain_text--><%= @message.body.to_plain_text %><!--/RC:plain_text-->
ERB

routes = File.join(app, "config/routes.rb")
src = File.read(routes)
unless src.include?("richtext_corpus#show")
  cut = src.rindex(/^end\b/) or abort "no closing `end` in #{routes}"
  src = src[0...cut] + %(  get "_richtext/:id" => "richtext_corpus#show"\n) + src[cut..]
  # Replace, never write through: the Rails tree is a hardlinked copy of
  # the oracle, and writing in place would edit the oracle's file too.
  File.delete(routes)
  File.write(routes, src)
end
puts "overlay: /_richtext/:id"
