#!/usr/bin/env ruby
# The runtime's wire contracts with Rails, held to Rails' own answers.
#
#   ruby tests/rails_compat_vectors.rb .           # every section, a table
#   ruby tests/rails_compat_vectors.rb . -v        # and every failing case
#
# THE ORACLE: tests/rails_compat/rails_compat.json, generated by
# once-campfire-rust's reference-tools/rails_compat_vectors.rb (MIT,
# vendored beside it) running INSIDE campfire under Rails in production
# mode, with a fixed SECRET_KEY_BASE and a frozen clock, both recorded
# in the file. Regenerated with our oracle's bundle
# (build/campfire-oracle), every deterministic section is byte-identical;
# the sections with randomness in them (IVs, salts, masks) are checked
# in the VERIFY direction only, which is the direction that decides
# whether a migrated user stays signed in.
#
# Each section drives the runtime function the emitted app calls for
# that contract — the cookie jar's verifier, `ActiveRecord::SignedId`,
# `ActionText::SignedGlobalId`, Active Storage's blob verifier,
# `GlobalID.param`, tep's cookie codec — not a re-derivation of it, so a
# pass means the app's own bytes agree with Rails'.
#
# A section the runtime does not implement is REPORTED as such, with the
# runtime.md entry that owns it, rather than skipped: encrypted cookies
# (the session store), CSRF tokens, bcrypt.
require "json"
require "time"

root = File.expand_path(ARGV[0] || ".")
VERBOSE = ARGV.include?("-v")
V = JSON.parse(File.read("#{root}/tests/rails_compat/rails_compat.json"))
SECRET = V.fetch("secret_key_base")

module Rails
  class App
    attr_accessor :secret_key_base
    def global_id_app = "campfire"
  end
  def self.application = @app ||= App.new
end
Rails.application.secret_key_base = SECRET

# The clock each case was minted or verified at.
class Time
  class << self
    attr_accessor :pinned
    alias_method :real_now, :now
    def now = pinned || real_now
  end
end

load "#{root}/runtime/spinel/base64.rb"
load "#{root}/runtime/spinel/message_digest_cruby.rb"
load "#{root}/runtime/ruby/action_controller/message_verifier.rb"
load "#{root}/runtime/ruby/active_record/signed_id.rb"
load "#{root}/runtime/spinel/tep/url.rb"

MV = ActionController::MessageVerifier

# GlobalID.param / .uri, and ActionText::SignedGlobalId, from the files
# that define them, without the rest of those files' load chains.
def load_module(path, name)
  src = File.read(path)
  start = src.index(/^(module|  module) #{name}\b/) or abort "no #{name} in #{path}"
  indent = src[start, 2] == "  " ? "  " : ""
  finish = src.index(/^#{indent}end\b/, start) or abort "no end of #{name}"
  src[start..finish + indent.length + 2]
end
module ActionText; end
eval(load_module("#{root}/runtime/ruby/rails.rb", "GlobalID"), TOPLEVEL_BINDING)
ActionText.module_eval(load_module("#{root}/runtime/ruby/action_text.rb", "SignedGlobalId"))

RESULTS = []
# Every gap below is written down in one place.
LEDGER = "runtime.md: Rails' signed-value contracts, held to Rails' vectors"
def section(name, owner: nil)
  @pass = 0
  @total = 0
  @fails = []
  yield
  RESULTS << [name, @pass, @total, owner]
  @fails.first(VERBOSE ? 100 : 0).each { |f| puts "  FAIL #{name}: #{f}" }
end

def check(label, got, want)
  @total += 1
  if got == want
    @pass += 1
  else
    @fails << "#{label}\n       want #{want.inspect[0, 200]}\n       got  #{got.inspect[0, 200]}"
  end
end

def at(iso)
  Time.pinned = iso ? Time.iso8601(iso) : Time.iso8601(V.fetch("now"))
  yield
ensure
  Time.pinned = nil
end

def exp_json(iso) = iso ? "\"#{iso}\"" : ""
BLOB_ID_CASE = ->(c) { c["name"] == "ActiveStorage" && c["purpose"] == "blob_id" }

# `signed_id` purposes are `<model_name.underscore>/<purpose>`, or the
# bare model name when there is none (what the lowering passes).
def signed_id_purpose(model, purpose)
  base = model.gsub("::", "/").gsub(/([a-z])([A-Z])/, '\1_\2').downcase
  purpose.to_s.empty? ? base : "#{base}/#{purpose}"
end

# ActiveSupport's JSON: Ruby's, with `<`, `>` and `&` escaped
# (`escape_html_entities_in_json`). U+2028/U+2029 go through as they
# are under 8.x defaults — the vectors say so.
def as_json(value)
  value.to_json.gsub("<", "\\u003c").gsub(">", "\\u003e").gsub("&", "\\u0026")
end

# ── --cases OUT: the same vectors, flattened for the spinel driver ────
# (tests/rails_compat/spinel_driver.rb). One case per line, tab-separated
# hex fields: op, arguments…, expected (a lone "-" = nil, "=" = the
# empty string). Only CLOCK-STABLE cases are written: the binary's verifier
# reads the real clock, so a case goes in when its verdict at the real
# now is the one it had at the vector's `now` — no expiry, or an expiry
# both instants fall on the same side of. The count left out is printed.
if (i = ARGV.index("--cases"))
  real_now = Time.real_now
  # "-" is nil and "=" the empty string: an empty hex field at the end of
  # a line is one `split("\t")` drops.
  hex = ->(x) { x.nil? ? "-" : (x.to_s.empty? ? "=" : x.to_s.b.unpack1("H*")) }
  exp_of = lambda do |signed|
    payload = signed.to_s.split("--").first.to_s
    env = [payload.tr("-_", "+/")].pack("a*").unpack1("m") rescue ""
    env = env.to_s
    inner = env[/"message":"([^"]*)"/, 1]
    env += inner.unpack1("m").to_s if inner
    t = env[/"exp":"([^"]+)"/, 1]
    t && (Time.iso8601(t) rescue nil)
  end
  stable = lambda do |signed, now_iso|
    exp = exp_of.(signed)
    exp.nil? || ((exp <= Time.iso8601(now_iso || V["now"])) == (exp <= real_now))
  end
  lines = []
  skipped = 0
  add = ->(*fields) { lines << fields.map(&hex).join("\t") }
  # An expected value the runtime cannot answer with — a JSON Integer or
  # object where it returns Strings — is marked so it cannot match by
  # accident, keeping the spinel count the CRuby count.
  typed = ->(v) { v.nil? || v.is_a?(String) ? v : "\x00typed:#{v.to_json}" }
  add.("secret", SECRET)   # line 0: what the binary signs with
  V["key_generator"].each { |c| add.("kg", c["salt"], c["length"], c["key_hex"]) }
  V["cookie_escaping"].each { |c| add.("unescape", c["wire"], c["parsed"]) }
  V["signed_cookies"]["verify"].each do |c|
    next skipped += 1 unless stable.(c["raw"], c["now"])
    add.("sc_verify", c["name"], c["raw"], typed.(c["expected"]))
  end
  V["signed_cookies"]["generate"].each do |c|
    add.("sc_envelope", c["name"], as_json(c["value"]), c["expires_at"] ? "\"#{c["expires_at"]}\"" : "null", c["raw"])
  end
  V["signed_cookies"]["generate"].each do |c|
    env = c["raw"].split("--").first.unpack1("m")
    rails_json = env[/"message":"([^"]*)"/, 1].unpack1("m").force_encoding("UTF-8")
    add.("json_encode", c["value"], rails_json)
    add.("json_decode", rails_json, c["value"])
  end
  V["app_verifiers"]["verify"].each do |c|
    next unless c["name"] == "ActiveStorage" && !c["purpose"].to_s.empty? && c["purpose"] != "blob_id"
    next skipped += 1 unless stable.(c["message"], c["now"])
    add.("as_data", c["message"], c["purpose"], c["expected_json"])
  end
  V["signed_ids"]["generate"].each do |c|
    next skipped += 1 if c["expires_at"]   # minted relative to the clock
    add.("sid_generate", c["id"], signed_id_purpose(c["model"], c["purpose"]), c["signed_id"])
  end
  V["signed_ids"]["verify"].each do |c|
    next skipped += 1 unless stable.(c["signed_id"], c["now"])
    want = c["expected"].is_a?(Integer) ? c["expected"].to_s : typed.(c["expected"])
    add.("sid_verify", c["signed_id"], signed_id_purpose(c["model"], c["purpose"]), want)
  end
  # (global_ids: plain base64, no crypto — the CRuby lane holds them.)
  V["sgids"]["generate"].each do |c|
    add.("sgid_generate", c["data"].to_json, c["purpose"], exp_json(c["expires_at"]), c["sgid"])
  end
  V["sgids"]["verify"].each do |c|
    next skipped += 1 unless stable.(c["sgid"], c["now"])
    add.("sgid_verify", c["sgid"], c["purpose"], c["expected"])
  end
  V["app_verifiers"]["generate"].each do |c|
    next unless c["name"] == "ActiveStorage" && !c["purpose"].to_s.empty?
    add.("as_generate", c["data_json"], c["purpose"], exp_json(c["expires_at"]), c["message"])
  end
  V["app_verifiers"]["verify"].select(&BLOB_ID_CASE).each do |c|
    next skipped += 1 unless stable.(c["message"], c["now"])
    add.("blob_verify", c["message"], c["expected_json"])
  end
  # Secrets whose derived keys hold a zero byte — none of the vectors'
  # keys does, and about one real SECRET_KEY_BASE in five does. The MAC
  # is OpenSSL's own, not the runtime's: an oracle independent of both.
  require "openssl"
  found = 0
  n = 0
  while found < 6
    secret = "nul-key-probe-#{n}"
    salt = [MV::SIGNED_COOKIE_SALT, "active_record/signed_id", "ActiveStorage"][found % 3]
    key = OpenSSL::PKCS5.pbkdf2_hmac(secret, salt, MV::ITERATIONS, 64, "SHA256")
    if key.include?("\0")
      digest = found.even? ? "SHA1" : "SHA256"
      add.("nul_key", secret, salt, digest, OpenSSL::HMAC.hexdigest(digest, key, "payload"))
      found += 1
    end
    n += 1
  end
  File.write(ARGV[i + 1], lines.join("\n") + "\n")
  puts "wrote #{lines.size - 1} cases, #{skipped} clock-dependent left out"
  exit
end

# ── key derivation ────────────────────────────────────────────────────
section("key_generator") do
  V["key_generator"].each do |c|
    got = if c["length"] == 64
      MV.derive_key(SECRET, c["salt"])
    else
      MessageDigest.pbkdf2_sha256(SECRET, c["salt"], MV::ITERATIONS, c["length"])
    end
    check(c["salt"], got.unpack1("H*"), c["key_hex"])
  end
end

# ── cookie value codec (tep's; the ruby family runs Rack's) ──────────
section("cookie_escaping.parse") do
  V["cookie_escaping"].each do |c|
    # Bytes, not encoding: CRuby labels the decoded String binary, spinel
    # has no label, and the app reads it as UTF-8 either way.
    check(c["wire"], Tep::Url.unescape(c["wire"]).b, c["parsed"].b)
  end
end
section("cookie_escaping.write", owner: LEDGER) do
  V["cookie_escaping"].each do |c|
    next if c["raw"].nil?
    check(c["raw"], Tep::Url.escape(c["raw"]), c["wire"])
  end
end

# ── signed cookies (the jar: session_token) ──────────────────────────
section("signed_cookies.verify", owner: LEDGER) do
  V["signed_cookies"]["verify"].each do |c|
    got = at(c["now"]) do
      MV.verified(SECRET, MV::SIGNED_COOKIE_SALT, c["raw"], "cookie." + c["name"], true)
    end
    check(c["case"], got == "" ? nil : got, c["expected"])
  end
end
section("signed_cookies.generate", owner: LEDGER) do
  V["signed_cookies"]["generate"].each do |c|
    # What the jar writes: `cookies.signed[:k] = v` (permanence unmodeled).
    got = at(nil) do
      MV.generate(SECRET, MV::SIGNED_COOKIE_SALT, c["value"], "cookie." + c["name"], true)
    end
    check("#{c["name"]} #{c["value"].inspect}", got, c["raw"])
  end
end
section("signed_cookies.generate_envelope") do
  # The envelope alone, given the expiry Rails' jar puts in it: does the
  # runtime spell a message exactly as Rails does?
  V["signed_cookies"]["generate"].each do |c|
    got = MV.envelope(SECRET, MV::SIGNED_COOKIE_SALT, as_json(c["value"]), "cookie." + c["name"],
                      c["expires_at"] ? "\"#{c["expires_at"]}\"" : "null", true)
    check("#{c["name"]} #{c["value"].inspect}", got, c["raw"])
  end
end

# ── the runtime's JSON string codec, against the JSON inside Rails' own
# signed cookies: the bytes Rails' serializer wrote for each value.
section("json_string") do
  V["signed_cookies"]["generate"].each do |c|
    env = c["raw"].split("--").first.unpack1("m")
    rails_json = env[/"message":"([^"]*)"/, 1].unpack1("m").force_encoding("UTF-8")
    check("encode #{c["value"].inspect}", MV.json_string(c["value"]), rails_json)
    check("decode #{c["value"].inspect}", MV.json_value(rails_json), c["value"])
  end
end

# ── signed ids (`record.signed_id`, `find_signed`) ───────────────────

section("signed_ids.generate") do
  V["signed_ids"]["generate"].each do |c|
    got = at(nil) do
      exp = c["expires_at"] ? ((Time.iso8601(c["expires_at"]) - Time.now).to_i) : 0
      ActiveRecord::SignedId.generate(c["id"], signed_id_purpose(c["model"], c["purpose"]), exp)
    end
    check("#{c["model"]} #{c["id"]} #{c["purpose"]}", got, c["signed_id"])
  end
end
section("signed_ids.verify", owner: LEDGER) do
  V["signed_ids"]["verify"].each do |c|
    got = at(c["now"]) do
      ActiveRecord::SignedId.verified_id(c["signed_id"], signed_id_purpose(c["model"], c["purpose"]))
    end
    check(c["case"], got == 0 ? nil : got, c["expected"])
  end
end

# ── GlobalID params and signed GlobalIDs (Action Text attachables) ───
section("global_ids") do
  V["global_ids"].each do |c|
    check(c["gid"], GlobalID.param(c["model_name"], c["id"]), c["param"])
  end
end
section("sgids.generate") do
  V["sgids"]["generate"].each do |c|
    got = at(nil) do
      MV.gid_envelope(SECRET, ActionText::SignedGlobalId::SALT, c["data"].to_json, c["purpose"], exp_json(c["expires_at"]))
    end
    check("#{c["data"]} #{c["purpose"]}", got, c["sgid"])
  end
end
section("sgids.verify", owner: LEDGER) do
  V["sgids"]["verify"].each do |c|
    got = at(c["now"]) do
      json = MV.verified_data_json(SECRET, ActionText::SignedGlobalId::SALT, c["sgid"], c["purpose"], true)
      json == "" ? nil : MV.json_value(json)
    end
    check(c["case"], got, c["expected"])
  end
end

# ── Active Storage's verifier (blob URLs, disk keys) ─────────────────
# `blob_id` is the one that lives: it is in every attachment URL a page,
# an email or a browser cache holds. It goes through what
# ActiveStorage::Blob#signed_id / .find_signed call.
BLOB_ID = BLOB_ID_CASE
section("app_verifiers.blob_id") do
  V["app_verifiers"]["generate"].select(&BLOB_ID).each do |c|
    got = MV.gid_envelope(SECRET, "ActiveStorage", c["data_json"], "blob_id", exp_json(c["expires_at"]))
    check("generate #{c["data_json"]}", got, c["message"])
  end
  V["app_verifiers"]["verify"].select(&BLOB_ID).each do |c|
    got = at(c["now"]) do
      json = MV.verified_data_json(SECRET, "ActiveStorage", c["message"], "blob_id", true)
      json == "" ? nil : json
    end
    check(c["case"], got, c["expected_json"])
  end
end
# The other purposes' ENVELOPE, on the same verifier. The runtime's
# disk_key / blob_token PAYLOADS are its own (`|`-joined, not Rails'
# JSON object), so these five-minute tokens are ours to read only —
# ledgered; what is checked here is that the envelope around them is
# Rails'.
section("app_verifiers.envelope") do
  V["app_verifiers"]["generate"].each do |c|
    next unless c["name"] == "ActiveStorage" && !c["purpose"].to_s.empty? && c["purpose"] != "blob_id"
    got = MV.gid_envelope(SECRET, "ActiveStorage", c["data_json"], c["purpose"], exp_json(c["expires_at"]))
    check("generate #{c["purpose"]}", got, c["message"])
  end
end

# The data the other Active Storage tokens carry, read back: objects
# with commas and escaped quotes in them (`blob_key`'s disposition).
section("app_verifiers.data") do
  V["app_verifiers"]["verify"].each do |c|
    next unless c["name"] == "ActiveStorage" && !c["purpose"].to_s.empty? && c["purpose"] != "blob_id"
    got = at(c["now"]) do
      json = MV.verified_data_json(SECRET, "ActiveStorage", c["message"], c["purpose"], true)
      json == "" ? nil : json
    end
    check(c["case"], got, c["expected_json"])
  end
end

# ── contracts the runtime does not implement ─────────────────────────
{
  "encrypted_cookies" => LEDGER,
  "csrf" => LEDGER,
  "passwords" => LEDGER,
}.each do |name, owner|
  n = V[name].is_a?(Hash) ? V[name].values.sum { |v| v.is_a?(Array) ? v.size : 0 } : V[name].size
  RESULTS << [name, 0, n, "NOT IMPLEMENTED — #{owner}"]
end

puts format("%-32s %9s  %s", "section", "match", "")
RESULTS.each do |name, pass, total, owner|
  mark = pass == total ? "ok" : "--"
  note = pass == total ? "" : (owner || "UNLEDGERED")
  puts format("%-32s %4d/%-4d %s %s", name, pass, total, mark, note)
end
puts "done"
