//! The spinel lane's request-params builder (`runtime/spinel/param_builder.rb`)
//! against Rails' own answers.
//!
//! `tests/params_vectors/params_vectors.json` is 2,755 query strings and
//! what `ActionDispatch::ParamBuilder.from_query_string` makes of them —
//! nested hashes and arrays, `nil` for a key with no `=`, and null where
//! Rails raises (a 400). Generated by the vendored
//! `tests/params_vectors/params_vectors.rb` (from once-campfire-rust);
//! regenerated with our oracle's bundle it is byte-identical.
//!
//! Two lanes over the same vectors: CRuby (always), and the builder
//! compiled by spinel (`#[ignore]`, needs `spinel` on PATH — CI runs it
//! beside the other spinel-compiled drivers):
//!
//!     PATH=$HOME/git/spinel/bin:$PATH cargo test --test spinel_param_builder -- --ignored

use std::path::{Path, PathBuf};
use std::process::Command;

const CASES: usize = 2755;

fn root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

fn assert_all_match(stdout: &str, stderr: &str) {
    // `done` is the last line; its absence means the driver died part
    // way, which an absence of FAIL lines alone would read as a pass.
    assert!(
        stdout.lines().any(|l| l == "done"),
        "driver did not finish\n=== stdout ===\n{stdout}\n=== stderr ===\n{stderr}"
    );
    let want = format!("{CASES}/{CASES} match Rails");
    assert!(stdout.lines().any(|l| l == want), "params diverge from Rails\n{stdout}");
}

#[test]
fn the_param_builder_matches_rails_under_cruby() {
    let out = Command::new("ruby")
        .arg(root().join("tests/spinel_param_builder.rb"))
        .arg(root())
        .output()
        .expect("ruby is on PATH");
    assert_all_match(&String::from_utf8_lossy(&out.stdout), &String::from_utf8_lossy(&out.stderr));
}

fn scratch_dir() -> PathBuf {
    let base = option_env!("CARGO_TARGET_TMPDIR")
        .map(PathBuf::from)
        .unwrap_or_else(std::env::temp_dir);
    base.join("roundhouse-spinel-param-builder")
}

#[test]
#[ignore]
fn the_param_builder_matches_rails_compiled_by_spinel() {
    let scratch = scratch_dir();
    let _ = std::fs::remove_dir_all(&scratch);
    std::fs::create_dir_all(&scratch).expect("mkdir scratch");
    for (from, to) in [
        ("runtime/spinel/param_builder.rb", "param_builder.rb"),
        ("tests/params_vectors/canon.rb", "canon.rb"),
        ("tests/params_vectors/spinel_driver.rb", "driver.rb"),
    ] {
        std::fs::copy(root().join(from), scratch.join(to)).expect("copy");
    }
    let cases = Command::new("ruby")
        .arg(root().join("tests/spinel_param_builder.rb"))
        .arg(root())
        .arg("--cases")
        .arg(scratch.join("cases.tsv"))
        .output()
        .expect("ruby is on PATH");
    assert!(cases.status.success(), "writing the case file failed: {}", String::from_utf8_lossy(&cases.stderr));

    let build = Command::new("spinel")
        .args(["driver.rb", "-o", "driver"])
        .current_dir(&scratch)
        .output()
        .expect("spinel is on PATH");
    assert!(
        build.status.success(),
        "spinel failed to compile the driver\n=== stdout ===\n{}\n=== stderr ===\n{}",
        String::from_utf8_lossy(&build.stdout),
        String::from_utf8_lossy(&build.stderr)
    );
    let run = Command::new(scratch.join("driver"))
        .arg(scratch.join("cases.tsv"))
        .output()
        .expect("run driver");
    assert_all_match(&String::from_utf8_lossy(&run.stdout), &String::from_utf8_lossy(&run.stderr));
}
