# Writes the emit half of the model differential into a copy of campfire:
# scenario.rb's statements as the body of an overlay controller action,
# and a route to it. The SAME lines Rails runs, so the two halves cannot
# drift: fixture lookups (`fx(Room, :designers)`) become `Room.find(<id>)`
# with Rails' own `ActiveRecord::FixtureSet.identify`, and the lines that
# only make sense in `rails runner` (the job adapter, the helper, the
# closing `puts`) are dropped — the harness holds jobs on each lane
# instead.
#
#   ruby tests/db_differential/overlay.rb <campfire copy>
require "zlib"

app = ARGV.fetch(0)
here = File.dirname(__FILE__)

# `ActiveRecord::FixtureSet.identify(label)` for an integer primary key.
MAX_ID = 2**30 - 1
def identify(label) = Zlib.crc32(label.to_s) % MAX_ID

body = []
File.readlines(File.join(here, "scenario.rb")).each do |line|
  next if line.start_with?("#") || line.strip.empty?
  next if line.start_with?("ActiveJob::Base.queue_adapter", "def fx", "puts ")
  if (m = line.match(/\A(\w+(?:, \w+)*) = %i\[([\w ]+)\]\.map \{ fx\((\w+), _1\) \}\s*\z/))
    names = m[1].split(", ")
    labels = m[2].split
    raise "names and labels differ: #{line}" unless names == labels
    names.each { |n| body << "#{n} = #{m[3]}.find(#{identify(n)})" }
    next
  end
  line = line.gsub(/fx\(((?:\w|::)+), :(\w+)\)/) { "#{$1}.find(#{identify($2)})" }
  raise "an fx lookup survived: #{line}" if line.include?("fx(")
  body << line.chomp
end

# Each statement on its own, so one that raises is RECORDED and the rest
# still run: a single run then names every statement the emit cannot do,
# and the table diff shows the effect of all the others. (A statement
# that fails can take a later one with it — a local it assigns stays nil
# — which the failure list makes plain.) The fixture lookups that open
# the scenario stay outside: nothing after them means anything without
# them.
setup, steps = body.partition { |l| l.match?(/\A\w+ = User\.find\(\d+\)\z/) || l.start_with?("Current.user =") }
guarded = steps.each_with_index.map do |line, i|
  <<~STEP.chomp
    begin
      #{line}
    rescue StandardError => e
      failures << "#{i + 1}: " + #{line.dump} + " -- " + e.class.name + ": " + e.message
    end
  STEP
end

controller = <<~RUBY
  # GENERATED by roundhouse's tests/db_differential/overlay.rb from
  # once-campfire-rust's model scenario — not part of campfire.
  class DifferentialScenariosController < ApplicationController
    allow_unauthenticated_access
    skip_forgery_protection

    def show
  #{setup.map { |l| "    #{l}" }.join("\n")}
      failures = []
  #{guarded.map { |b| b.gsub(/^/, "    ") }.join("\n")}
      render plain: failures.empty? ? "ok" : failures.join("\\n")
    end
  end
RUBY
File.write(File.join(app, "app/controllers/differential_scenarios_controller.rb"), controller)

routes = File.join(app, "config/routes.rb")
src = File.read(routes)
unless src.include?("differential_scenarios#show")
  cut = src.rindex(/^end\b/) or abort "no closing `end` in #{routes}"
  src = src[0...cut] + %(  get "_differential/scenario" => "differential_scenarios#show"\n) + src[cut..]
  File.write(routes, src)
end
puts "overlay: #{steps.size} statements, each guarded"
