//! Schema SQL — emits `app/schema_sql.py` exposing the
//! target-neutral DDL as `CREATE_TABLES`.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// `app/schema_sql.py` — Python module exposing the target-neutral
/// DDL as `CREATE_TABLES`. sqlite3's `executescript` handles
/// multi-statement strings directly, so no splitting needed.
pub(super) fn emit_schema_sql(app: &App) -> EmittedFile {
    let ddl = crate::emit::shared::schema_sql::render_schema_sql(&app.schema);
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    // SQL identifier quotes must not terminate the host-language literal.
    writeln!(s, "CREATE_TABLES = {}", super::shared::py_string_literal(&ddl)).unwrap();
    EmittedFile {
        path: PathBuf::from("app/schema_sql.py"),
        content: s,
    }
}
